name: "Pull Request Checks"
on:
  pull_request:
    types: [synchronize, opened]

jobs:
  check_bundlesize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        # For now, install dev dependencies too, since we rely on vue-cli-service

      - uses: jackyef/bundlewatch-gh-action@0.2.0
        with:
          build-script: npm run build
          bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
          bundlewatch-config: .github/.bundlewatch.config.js
  