name: "Pull Request Checks"
on:
  - pull_request

jobs:
  check_bundlesize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0

      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  